version: '3.4'

services: 
    mongoDbNewHorizons:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017